version: "3.4"
services:
  db:
    container_name: "postgresql_db"
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgredata:/var/lib/postgresql/data
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: "app"
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always  

volumes:
  postgredata:
